from pygame import Color

""" Configuration """
SCREEN_SIZE = WIDTH, HEIGHT = (600, 600)

# Careful, CELL_COUNT must be dividable by SCREEN_SIZE.
UNIVERSE_NUM_ROWS = 50
UNIVERSE_NUM_COLS = 50

CELLS_SIZE_WIDTH = WIDTH / UNIVERSE_NUM_ROWS
CELLS_SIZE_HEIGHT = WIDTH / UNIVERSE_NUM_COLS

""" Graphics """

BACKGROUND = Color(0, 0, 0)
COLOR_CELL_ALIVE = Color(255, 255, 255)
COLOR_CELL_DEAD = Color(0, 0, 0)

