from pygame import Color

""" Configuration """
SCREEN_SIZE = WIDTH, HEIGHT = (600, 600)
COUNT_OF_CELLS = 100 # I DONT LIKE THIS
CELLS_PER_WIDTH = int(WIDTH / COUNT_OF_CELLS)
COUNT_PER_HEIGHT = int(HEIGHT / COUNT_OF_CELLS)

BACKGROUND = (255, 255, 255)
COLOR_CELL_ALIVE = Color(255, 255, 255)
COLOR_CELL_DEAD = Color(0, 0, 0)

FPS = 100


